import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { chromeFixture } from './fixtures/chrome.mjs';
const f = chromeFixture(); f.grants.add('https://canvas.example.test/*');
f.chrome.storage.local.data.enabledOrigins = ['https://canvas.example.test'];
globalThis.chrome = f.chrome; globalThis.indexedDB = new IDBFactory();
const { senderKind } = await import('../extension/background.mjs');
const own = { id: 'test-extension', url: 'chrome-extension://test-extension/options.html' };
const page = { id: 'test-extension', url: 'https://canvas.example.test/client', tab: { id: 1 } };
const enabled = ['https://canvas.example.test'];
assert.equal(senderKind(own, 'test-extension'), 'settings'); assert.equal(senderKind(page, 'test-extension', enabled), 'page');
for (const sender of [{ ...page, id: 'other' }, { ...page, url: 'https://unselected.example.test/client' }, { ...page, url: 'https://canvas.example.test.evil.test/client' }, { ...page, tab: undefined }]) assert.equal(senderKind(sender, 'test-extension', enabled), null);
const listener = f.chrome.runtime.onMessage.listeners[0], send = (message, sender) => new Promise(resolve => listener(message, sender, resolve));
for (const action of ['setSettings', 'setPreferences', 'getSettings', 'getSharedSettings', 'setSharedSettings', 'setProfileSettings', 'probe', 'exportTranslations', 'importTranslations', 'getCacheStats', 'getPersonalTranslation', 'setPersonalTranslation', 'removePersonalTranslation', 'clearCache', 'getPageContext', 'enableSites', 'disableSites', 'getProfiles', 'createProfile', 'renameProfile', 'bindPageProfile', 'selectEditorProfile']) assert.equal((await send({ action, payload: {} }, page)).ok, false, action);
assert.equal((await send({ action: 'setSettings', payload: { provider: 'openai', apiBase: 'https://api.example.test/v1', model: 'test-model', apiKey: 'TEST_ONLY_NOT_SECRET' } }, own)).ok, true);
const preferences = await send({ action: 'getPreferences' }, page); assert(preferences.ok);
assert(preferences.data.profileRequired && !preferences.data.profileId && !preferences.data.storyEnabled);
const unbound = await send({ action: 'translate', profileId: 'default', payload: { items: [{ id: 'unbound', text: 'テスト' }] } }, page);
assert(unbound.data.profileRequired); assert.equal(unbound.data.items[0].text, 'テスト');
assert((await send({ action: 'translate', payload: { items: [] } }, page)).ok === false);
const context = (await send({ action: 'getPageContext' }, own)).data;
assert.equal(context.profileId, null);
assert((await send({ action: 'bindPageProfile', payload: { scope: context.scope, tabId: context.tabId, id: 'default' } }, own)).ok);
assert(!Object.hasOwn(preferences.data, 'apiBase')); assert(!JSON.stringify(preferences).includes('TEST_ONLY_NOT_SECRET'));
assert.equal((await send({ action: 'setPreferences', payload: { paused: true } }, page)).ok, false);
const paused = await send({ action: 'setPreferences', payload: { paused: true } }, own); assert(paused.ok && paused.data.paused);
const broadcast = f.injected.at(-1); assert.deepEqual(broadcast.target.frameIds, [0]); assert.equal(broadcast.args[0].paused, true);
assert(!JSON.stringify(broadcast.args).includes('TEST_ONLY_NOT_SECRET')); assert(!Object.hasOwn(broadcast.args[0], 'apiBase'));
const held = await send({ action: 'translate', payload: { items: [{ id: 'held', text: 'メニュー', kind: 'ui' }] } }, page);
assert(held.ok && held.data.paused); assert.equal(held.data.items[0].text, 'メニュー');
assert.equal(senderKind({ ...own, url: 'chrome-extension://test-extension/update.html' }, 'test-extension'), 'settings');
const second = (await send({ action: 'createProfile', payload: { name: 'Second' } }, own)).data;
assert(second.hasApiKey && second.model === 'test-model');
assert((await send({ action: 'setSharedSettings', payload: { targetLanguage: 'en', historyMaxEntries: 8 } }, own)).ok);
for (const profileId of ['default', second.profileId]) { const settings = (await send({ action: 'getSettings', profileId }, own)).data; assert.equal(settings.targetLanguage, 'en'); assert.equal(settings.historyMaxEntries, 8); }
assert.equal((await send({ action: 'setProfileSettings', profileId: second.profileId, payload: { targetLanguage: 'ko' } }, own)).ok, false);
assert((await send({ action: 'setProfileSettings', profileId: second.profileId, payload: { customPrompt: 'Names: アリス = Alice.' } }, own)).ok);
assert.equal((await send({ action: 'getSettings', profileId: 'default' }, own)).data.customPrompt, '');
const wrongLanguage = await send({ action: 'setPersonalTranslation', profileId: second.profileId, targetLanguage: 'zh-CN', payload: { original: 'アリス', translation: 'Wrong language' } }, own);
assert.equal(wrongLanguage.ok, false); assert(wrongLanguage.error.includes('目标语言'));
assert.equal((await send({ action: 'getPageContext' }, own)).data.profileId, 'default');
assert.equal((await send({ action: 'getPreferences', profileId: second.profileId }, page)).data.profileId, 'default', 'A page must not select a foreign profile');
assert((await send({ action: 'setPreferences', profileId: 'default', payload: { paused: false } }, own)).ok);
f.grants.add('https://api.example.test/*');
const source = 'これは遅い応答です。'; let release;
globalThis.fetch = async () => new Promise(resolve => { release = resolve; });
const late = send({ action: 'translate', payload: { items: [{ id: 'late', text: source }] } }, page);
for (let attempt = 0; !release && attempt < 50; attempt++) await new Promise(resolve => setImmediate(resolve));
assert(release);
assert((await send({ action: 'bindPageProfile', payload: { scope: context.scope, tabId: context.tabId, id: second.profileId } }, own)).ok);
release({ ok: true, json: async () => ({ choices: [{ message: { content: '旧 Profile 的响应' } }] }) });
const stale = await late; assert(stale.ok && stale.data.profileChanged); assert.equal(stale.data.items[0].text, source);
const lastBroadcast = f.injected.at(-1).args[0]; assert.equal(lastBroadcast.profileId, second.profileId);
assert(!JSON.stringify(lastBroadcast).includes('TEST_ONLY_NOT_SECRET'));
f.frames[0].url = 'https://canvas.example.test/unseen';
assert((await send({ action: 'getPreferences' }, page)).data.profileRequired);
assert.equal((await send({ action: 'bindPageProfile', payload: { scope: context.scope, tabId: context.tabId, id: 'default' } }, own)).ok, false);
f.grants.delete('https://canvas.example.test/*'); assert.equal((await send({ action: 'getPreferences' }, page)).ok, false);
console.log('Background: trusted settings, credentials, unbound pages, per-page selection, stale profile responses, page operation restrictions and permission revocation passed.');
