import assert from 'node:assert/strict';
import { createSiteAccess, webOrigin } from '../extension/site-access.mjs';
import { chromeFixture } from './fixtures/chrome.mjs';
const f = chromeFixture(), sites = createSiteAccess(f.chrome); await sites.ready;
assert.equal(f.registered.size, 0);
f.grants.add('https://api.example.test/*'); await sites.synchronize(); assert.equal(f.registered.size, 0);
for (const origin of ['https://canvas.example.test', 'https://content.example.test']) f.grants.add(origin + '/*');
await sites.enable(['https://canvas.example.test', 'https://content.example.test'], 1);
assert.equal(f.registered.size, 2);
assert([...f.registered.values()].every(script => script.matches.length === 2 && script.allFrames && script.persistAcrossSessions));
assert(f.registered.get('unity-web-runtime').world === 'MAIN');
assert.deepEqual(f.injected.map(call => call.target.frameIds), [[0, 1], [0, 1]]);
assert(!f.injected.some(call => call.target.allFrames));
const context = await sites.context(); assert(context.origins.filter(row => row.enabled).length === 2);
const stored = structuredClone(f.chrome.storage.local.data.enabledOrigins);
await assert.rejects(sites.enable(['https://unselected.example.test'], 1), /允许/);
await assert.rejects(sites.enable(['https://not-in-page.example.test'], 1), /网页已变化/);
assert.deepEqual(f.chrome.storage.local.data.enabledOrigins, stored);
f.grants.delete('https://content.example.test/*'); await sites.synchronize();
assert([...f.registered.values()].every(script => script.matches.length === 1));
await sites.disable(['https://canvas.example.test'], 1); assert.equal(f.registered.size, 0);
assert(f.injected.at(-1).func.toString().includes('__UnityWebTranslator'));
assert.throws(() => webOrigin('file:///secret')); assert.throws(() => webOrigin('https://user:password@canvas.example.test'));
console.log('Site policy: initial isolation, provider exclusion, cross-frame authorization, selective injection, revocation, and disable checks passed.');
